[project]
name = "final"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.12.4",
    "fastapi>=0.115.0",
    "uvicorn>=0.31.0",
    "boto3>=1.35.20",
]
